export const BookingsLocators = {
  url: 'http://aviro-ui-qa.us-east-2.elasticbeanstalk.com/operator/bookings',
  pageHeading: 'Booking',
  createBookingButton: 'Create Booking',
  customerCombobox: 'Customer search results',
  locationCombobox: 'Location search results',
  optionLabel: '.MuiTypography-root.MuiTypography-body1.drawer-searchable-select-field__option-label',
  dropoffRadio: 'Dropoff',
  stackRadio: 'Stack',
  onePieceRadio: 'One piece',
  nextButton: 'Next',
  yesRadio: 'Yes',
  createBookingSubmit: 'Create booking',
  successMessage: /was created successfully/,
  bookingCreatedToast: 'Booking created',
  bookingIdPattern: /BK\d+/,
  searchPlaceholder: /search/i,
  searchButton: 'Search',
  dayRateInput: 'input.MuiInputBase-inputAdornedStart',
  dayRateValue: '500',
};
